### ISSUE TITLE
Unable to install pycddlib

### ISSUE THREAD

**Issue by vyass612** [IBM/LOA#14]
I have tried to install pycddlib in the requirements.txt file but am running into an error

```
Installing collected packages: pycddlib
  Running setup.py install for pycddlib ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycddlib did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /home/vboxuser/anaconda3/envs/loa/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      /home/vboxuser/anaconda3/envs/loa/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      skipping 'cdd.c' Cython extension (up-to-date)
      building 'cdd' extension
      creating build
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/cddlib
      creating build/temp.linux-x86_64-cpython-38/cddlib/lib-src
      gcc -pthread -B /home/vboxuser/anaconda3/envs/loa/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DGMPRATIONAL -Icddlib/lib-src -I/home/vboxuser/anaconda3/envs/loa/include/python3.8 -c cdd.c -o build/temp.linux-x86_64-cpython-38/cdd.o
      In file included from cddlib/lib-src/cdd.h:17,
                       from cdd.c:601:
      cddlib/lib-src/cddmp.h:30:11: fatal error: gmp.h: No such file or directory
         30 |  #include "gmp.h"
            |           ^~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycddlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
Im unsure as to what I am missing here, kindly suggest a solution. Thank you :)

**Comment by vyass612** [comment]
After using this, I am able to install pycddlib **2.1.6** using https://pycddlib.readthedocs.io/en/latest/quickstart.html
Will close the issue once the model fully trains

**Comment by daiki-kimura** [comment]
@vyass612 Hi, than you for your feedback.
From our side (especially it is ubuntu), we can install with this requirements.txt. 
Which environment did you use? do you think is it better to change this file?
https://github.com/IBM/LOA/blob/main/requirements.txt

**Comment by vyass612** [comment]
Hi @daiki-kimura.
I tried to download the specific version mentioned in the requirements.txt, but was getting errors. The code seems to work using pycddlib version 2.1.6 for now. But I have run into another error mentioned in the open issues page. I am not completely sure if this pycddlib version is linked to the error that I have now unfortunately.
